name: "Create Release"

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: Bump type of release
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Bump version
        run: npm version ${{ inputs.bump_type }}
      - name: Push changes to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
          git push --tags
